### ISSUE TITLE
fpsCounter didn't show fps counter in window's title

### ISSUE THREAD

**Issue by haxpor** [krOoze/Hello_Triangle#2]
I faced the problem of `fpsCounter` which relates directly to `VK_LAYER_LUNARG_monitor` didn't show FPS counter on window's title on Ubuntu 19.10.

It happened to me in another glfw-based application as well. But `vkcube` as bundled from SDK works fine and able to show FPS counter.

Any ideas of what problem might be?

**Comment by krOoze** [comment]
The FPS counter does not work with Wayland, I think. Probably hard to implement given how Wayland works (you can't be sure which, if any protocol the user uses for window decorations).
IIRC it works in X, and definitely in win32. So if you want to just try it, you could relog to X session in Ubuntu.

Anyway, this is probably just a problem of [LunarG/VulkanTools/](https://github.com/LunarG/VulkanTools/) repo, which hosts Monitor layer. Nothing I can do with it here, except perhaps implement my own FPS counting, but that is bit outside the scope of the simple example.

**Comment by haxpor** [comment]
Thank you very much! I agree it is not this repo's bug, I'm about to close it before you just did :)

By the way, above I tested on X11, not wayland. I'll keep my eye open for this issue.

**Comment by krOoze** [comment]
@haxpor, I investigated a bit and Monitor is only supported on Win32 and XCB. I guess GLFW uses Xlib?

I have a toy XCB implementation here though. You can try it with `cmake -DWSI=VK_USE_PLATFORM_XCB_KHR ..`. The Monitor layer for that platform is not great either; it seems to erase the original window title text...

**Comment by haxpor** [comment]
@krOoze Thanks! I tested it again with XCB, now framerates shows up. I also checked, GLFW uses xlib on my case but that's because I didn't have any XCB lib installed on my machine. Good to know now I probably should base on XCB when dealing with Vulkan.
