### ISSUE TITLE
Missing return statement in VulkanIntrospection.h

### ISSUE THREAD

**Issue by yomboprime** [krOoze/Hello_Triangle#5]
I think a ```return``` statement should go here. The compiler throws a warning about unused expression ```(src/VulkanIntrospection.h:40:49: warning: statement has no effect [-Wunused-value])```

https://github.com/krOoze/Hello_Triangle/blob/a8844e947870b0be1d0e9f535ebac71ad90c0e34/src/VulkanIntrospection.h#L40

**Comment by krOoze** [comment]
Indeed. Thank you!
