### ISSUE TITLE
linux support

### ISSUE THREAD

**Issue by tari3x** [krOoze/Hello_Triangle#6]
Would love to try running this on linux. My goal is to translate the example into ocaml, using https://github.com/Octachron/olivine.

**Comment by tari3x** [comment]
Oh, I didn't notice the manual build section. I'll try that. 

Would be nice if cmake just worked though!

**Comment by tari3x** [comment]
Worked, sorry for the noise!

**Comment by krOoze** [comment]
Cmake should work per [the linux CI](https://github.com/krOoze/Hello_Triangle/runs/916738233?check_suite_focus=true).

Otherwise I need debug info.
