### ISSUE TITLE
failing VULKAN_VALIDATION

### ISSUE THREAD

**Issue by tari3x** [krOoze/Hello_Triangle#7]
I compiled HelloTriangle succesfully, but when trying to run it I get 

```
ERROR: Terminated due to an uncaught exception: VULKAN_VALIDATION is enabled but VK_LAYER_KHRONOS_validation layers are not supported!
```

Does this mean my version of Vulkan is wrong? I use SDK 1.2.148.1.

**Comment by krOoze** [comment]
`VULKAN_VALIDATION` is my C macro that controls if Vulkan validation layers should run. I have it connected to `_NDEBUG` (so debug build runs layers while release build does not).

That means the `VK_LAYER_KHRONOS_validation` layer has to be installed (and reported by Vulkan), when Validation is supposed to be run. Check with `vulkaninfo` (or VulkanCapsViewer) that this layer is there. Frequent issue is that the tarball  SDK does not set the necessary env for the driver to find the layers, and that has to be done manually per SDK manual.
