### ISSUE TITLE
Validation Error caused by vkAllocateMemory-deviceCoherentMemory

### ISSUE THREAD

**Issue by MrROBUST** [krOoze/Hello_Triangle#9]
Hello.

When I ran this example on my ryzen 2200g video chip with validation layers enabled, I have the following warning, raised from `initMemory` function:

> VALIDATION+ERROR: [Device(0x1E7AB642BC0)]: VUID-vkAllocateMemory-deviceCoherentMemory-02790(-2010063723), "Validation Error: [ VUID-vkAllocateMemory-deviceCoherentMemory-02790 ] Object 
> 0: handle = 0x1e7ab642bc0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x8830dc95 | vkAllocateMemory: attempting to allocate memory type 6, which includes the VK_MEMORY_PROPERTY_DEVICE_COHERENT_BIT_AMD memory property, but the deviceCoherentMemory feature is not enabled. The Vulkan spec states: If the deviceCoherentMemory feature is not enabled, pAllocateInfo->memoryTypeIndex must not identify a memory type supporting VK_MEMORY_PROPERTY_DEVICE_COHERENT_BIT_AMD. (https://vulkan.lunarg.com/doc/view/1.2.176.1/windows/1.2-extensions/vkspec.html#VUID-vkAllocateMemory-deviceCoherentMemory-02790)"

idk why this happens with `VK_MEMORY_PROPERTY_DEVICE_COHERENT_BIT` instead of `VK_MEMORY_PROPERTY_DEVICE_COHERENT_BIT_AMD`, but probably the VK_AMD_device_coherent_memory device extension must be enabled on AMD devices.

Seems this documentation is related: https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/vk_amd_device_coherent_memory.html

**Comment by krOoze** [comment]
Right, the main problem is I am not properly minimizing the used flags.

Bit of a grey area in the specification though. By the letter, it should be valid to use a memory type with unknown flags, and it would be compatibility breaking for an extension to forbid it. Discussion on this here: https://github.com/KhronosGroup/Vulkan-Docs/issues/1298

**Comment by krOoze** [comment]
I think the latest commit should silence the error for you.

**Comment by MrROBUST** [comment]
It works, thanks.

Also MSAA branch needs update of
```
frameMemory = initMemory<ResourceType::Image>(device, physicalDeviceMemoryProperties, frameImage,
                                              VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
```
with
```
frameMemory = initMemory<ResourceType::Image>(device, physicalDeviceMemoryProperties, frameImage,
                                              memoryTypePriority);
```

**Comment by krOoze** [comment]
I think I already updated it.
